routes/web.php
<?php
	/*
	Project Name: IonicEcommerce
	Project URI: http://ionicecommerce.com
	Author: VectorCoder Team
	Author URI: http://vectorcoder.com/
	Version: 1 -desktop
	*/
	header("Cache-Control: no-cache, must-revalidate");
	header('Access-Control-Allow-Origin:  *');
	header('Access-Control-Allow-Methods:  POST, GET, OPTIONS, PUT, DELETE');
	header('Access-Control-Allow-Headers:  Content-Type, X-Auth-Token, Origin, Authorization');

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/



/*
|--------------------------------------------------------------------------
| Admin controller Routes
|--------------------------------------------------------------------------
|
| This section contains all admin Routes
| 
|
*/

Route::group(['prefix' => 'admin'], function () {
	
	Route::group(['namespace' => 'Admin'], function () {

		Route::group(['middleware' => 'admin'], function () {
			Route::get('/dashboard/{reportBase}', 'AdminController@dashboard');
			Route::get('/post', 'AdminController@myPost');
			//show admin personal info record
			Route::get('/adminInfo', 'AdminController@adminInfo');

			/*
			| Help Customer to place an order
			*/
			Route::post('/addToCart', 'CartController@addToCart');
			Route::resource('users', 'UsersController');
		/*
		|--------------------------------------------------------------------------
		| categories/Product Controller Routes
		|--------------------------------------------------------------------------
		|
		| This section contains categories/Product Controller Routes
		| 
		|
		*/
			//main listingManufacturer
			Route::get('/manufacturers', 'AdminManufacturerController@manufacturers');
			Route::get('/addmanufacturer', 'AdminManufacturerController@addmanufacturer');
			Route::post('/addnewmanufacturer', 'AdminManufacturerController@addnewmanufacturer');
			Route::get('/editmanufacturer/{id}', 'AdminManufacturerController@editmanufacturer');
			Route::post('/updatemanufacturer', 'AdminManufacturerController@updatemanufacturer');
			Route::post('/deletemanufacturer', 'AdminManufacturerController@deletemanufacturer');



			//main categories
			Route::get('/categories', 'AdminCategoriesController@categories');
			Route::get('/addcategory', 'AdminCategoriesController@addcategory');
			Route::post('/addnewcategory', 'AdminCategoriesController@addnewcategory');
			Route::get('/editcategory/{id}', 'AdminCategoriesController@editcategory');
			Route::post('/updatecategory', 'AdminCategoriesController@updatecategory');
			Route::get('/deletecategory/{id}', 'AdminCategoriesController@deletecategory');

			//sub categories
			Route::get('/subcategories', 'AdminCategoriesController@subcategories');
			Route::get('/addsubcategory', 'AdminCategoriesController@addsubcategory');
			Route::post('/addnewsubcategory', 'AdminCategoriesController@addnewsubcategory');
			Route::get('/editsubcategory/{id}', 'AdminCategoriesController@editsubcategory');
			Route::post('/updatesubcategory', 'AdminCategoriesController@updatesubcategory');
			Route::get('/deletesubcategory/{id}', 'AdminCategoriesController@deletesubcategory');
			
			Route::post('/getajaxcategories', 'AdminCategoriesController@getajaxcategories');

			//products
			Route::get('/products', 'AdminProductsController@products');
			Route::get('/addproduct', 'AdminProductsController@addproduct');
			Route::post('/addnewproduct', 'AdminProductsController@addnewproduct');

			//add attribute against newly added product
			Route::get('/addproductattribute/{id}/', 'AdminProductsController@addproductattribute');
			Route::get('/addproductimages/{id}/', 'AdminProductsController@addproductimages');
			Route::post('/addnewdefaultattribute', 'AdminProductsController@addnewdefaultattribute');
			Route::post('/addnewproductattribute', 'AdminProductsController@addnewproductattribute');
			Route::post('/updateproductattribute', 'AdminProductsController@updateproductattribute');
			Route::post('/updatedefaultattribute', 'AdminProductsController@updatedefaultattribute');
			Route::post('/deleteproduct', 'AdminProductsController@deleteproduct');
			Route::post('/deleteproductattribute', 'AdminProductsController@deleteproductattribute');
			Route::post('/addnewproductimage', 'AdminProductsController@addnewproductimage');
			Route::post('/deletedefaultattribute', 'AdminProductsController@deletedefaultattribute');
			Route::post('editproductattribute', 'AdminProductsController@editproductattribute');
			Route::post('editdefaultattribute', 'AdminProductsController@editdefaultattribute');
			Route::post('addnewproductimagemodal', 'AdminProductsController@addnewproductimagemodal');
			Route::post('deleteproductattributemodal', 'AdminProductsController@deleteproductattributemodal');
			Route::post('deletedefaultattributemodal', 'AdminProductsController@deletedefaultattributemodal');

			//product attribute
			Route::post('/addnewproductimage', 'AdminProductsController@addnewproductimage');
			Route::post('editproductimage', 'AdminProductsController@editproductimage');
			Route::post('/updateproductimage', 'AdminProductsController@updateproductimage');
			Route::post('/deleteproductimagemodal', 'AdminProductsController@deleteproductimagemodal');
			Route::post('/deleteproductimage', 'AdminProductsController@deleteproductimage');
			Route::get('/editproduct/{id}', 'AdminProductsController@editproduct');
			Route::post('/updateproduct', 'AdminProductsController@updateproduct');	
			Route::post('/getOptions', 'AdminProductsController@getOptions');	
			Route::post('/getOptionsValue', 'AdminProductsController@getOptionsValue');	


			//Attribute
			Route::get('/attributes', 'AdminProductsController@attributes');
			Route::get('/addattributes', 'AdminProductsController@addattributes');
			Route::post('/addnewattributes', 'AdminProductsController@addnewattributes');
			Route::get('/editattributes/{id}/{language_id}', 'AdminProductsController@editattributes');
			Route::post('/updateattributes/', 'AdminProductsController@updateattributes');
			Route::post('/deleteattribute', 'AdminProductsController@deleteattribute');
			Route::post('/addattributevalue', 'AdminProductsController@addattributevalue');
			Route::post('/updateattributevalue', 'AdminProductsController@updateattributevalue');
			Route::post('/checkattributeassociate', 'AdminProductsController@checkattributeassociate');
			Route::post('/checkvalueassociate', 'AdminProductsController@checkvalueassociate');
			Route::post('/deletevalue', 'AdminProductsController@deletevalue');


			//manageAppLabel
			Route::get('/listingAppLabels', 'AdminAppLabelsController@listingAppLabels');
			Route::get('/addappkey', 'AdminAppLabelsController@addappkey');
			Route::post('/addNewAppLabel', 'AdminAppLabelsController@addNewAppLabel');
			Route::get('/editAppLabel/{id}', 'AdminAppLabelsController@editAppLabel');
			Route::post('/updateAppLabel/', 'AdminAppLabelsController@updateAppLabel');
			Route::get('/applabel', 'AdminAppLabelsController@manageAppLabel');


			//customers
			Route::get('/customers', 'AdminCustomersController@customers');
			Route::get('/addcustomers', 'AdminCustomersController@addcustomers');
			Route::post('/addnewcustomers', 'AdminCustomersController@addnewcustomers');


			//add adddresses against customers
			Route::get('/addaddress/{id}/', 'AdminCustomersController@addaddress');
			Route::post('/addNewCustomerAddress', 'AdminCustomersController@addNewCustomerAddress');
			Route::post('/editAddress', 'AdminCustomersController@editAddress');
			Route::post('/updateAddress', 'AdminCustomersController@updateAddress');
			Route::post('/deleteAddress', 'AdminCustomersController@deleteAddress');
			Route::post('/getZones', 'AdminCustomersController@getZones');
			//edit customer
			Route::get('/editcustomers/{id}', 'AdminCustomersController@editcustomers');
			Route::post('/updatecustomers', 'AdminCustomersController@updatecustomers');
			Route::post('/deletecustomers', 'AdminCustomersController@deletecustomers');

			//orders
			Route::get('/orders', 'AdminOrdersController@orders');	
			Route::get('/orderforclient', 'AdminOrdersController@orderforcustomer');	
			Route::get('/vieworder/{id}', 'AdminOrdersController@vieworder');
			Route::post('/updateOrder', 'AdminOrdersController@updateOrder');
			Route::post('/deleteOrder', 'AdminOrdersController@deleteOrder');
			
			//alert setting
			Route::get('/alertsetting', 'AdminSiteSettingController@alertSetting');
			Route::post('/updateAlertSetting', 'AdminSiteSettingController@updateAlertSetting');
			
			//generate application key
			Route::get('/generateKey', 'AdminSiteSettingController@generateKey');

			//countries
			Route::get('/countries', 'AdminTaxController@countries');
			Route::get('/addcountry', 'AdminTaxController@addcountry');
			Route::post('/addnewcountry', 'AdminTaxController@addnewcountry');
			Route::get('/editcountry/{id}', 'AdminTaxController@editcountry');
			Route::post('/updatecountry', 'AdminTaxController@updatecountry');
			Route::post('/deletecountry', 'AdminTaxController@deletecountry');

			//zones
			Route::get('/listingZones', 'AdminTaxController@listingZones');
			Route::get('/addZone', 'AdminTaxController@addZone');
			Route::post('/addNewZone', 'AdminTaxController@addNewZone');
			Route::get('/editZone/{id}', 'AdminTaxController@editZone');
			Route::post('/updateZone', 'AdminTaxController@updateZone');
			Route::post('/deleteZone', 'AdminTaxController@deleteZone');

			//tax class
			Route::get('/taxclass', 'AdminTaxController@taxclass');
			Route::get('/addtaxclass', 'AdminTaxController@addtaxclass');
			Route::post('/addnewtaxclass', 'AdminTaxController@addnewtaxclass');

app/User.php
<?php

namespace App;

use App\Permission;
use App\Role;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
	protected $table = 'users';
	
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
   
     public function roles(){
        return $this->belongsTo(Role::class,'role_id');
    }
     public function permissions() {
        return $this->belongsTo(Permission::class, 'permission_id');
  
     }
	
}

app/Http/Controllers/Admin/UsersController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\User;
use App\Role;
use Lang;
use Illuminate\Support\Facades\Validator;
use Illuminate\Foundation\Auth\RegistersUsers;

class UsersController extends Controller
{
    use RegistersUsers;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $title = array('pageTitle' => Lang::get("labels.Users"));
        $allusers = User::all();
        $roles = Role::all();
        return view('admin.users.list', $title, compact('allusers', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|max:255|unique:users',
            'password' => 'required|string|min:6|confirmed',
        ]);
    }

   protected function store(Request $request)
    {
        
        $users = new User();
        $users->name = $request->get('name');
        $users->email = $request->get('email');
        $users->role_id = $request->get('role_id');
        $users->password = bcrypt($request->get('password'));

        $users->save();
        return redirect()->route('users.index')
                          ->with('success', 'Staff has been onboarded successfully');

    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/users/list.blade.php
@extends('admin.layout')
@section('content')
<div class="content-wrapper"> 
        <!-- Content Header (Page header) -->
  <section class="content-header">
        <h1> {{ trans('labels.Addusers') }} <small>{{ trans('labels.Addusers') }}...</small> </h1>
        <ol class="breadcrumb">
           <li><a href="{{ URL::to('admin/dashboard/this_month') }}"><i class="fa fa-dashboard"></i> {{ trans('labels.breadcrumb_dashboard') }}</a></li>
          <li><a href="{{ URL::to('admin/listingusers')}}"><i class="fa fa-bars"></i> {{ trans('labels.ListAllusers') }}</a></li>
          <li class="active">{{ trans('labels.users') }}</li>
        </ol>
      </section>
      <section class="content"> 
            <!-- Info boxes --> 
            
            <!-- /.row -->
        
            <div class="row">
              <div class="col-md-12">
                <div class="box">
                  <div class="box-header">
                    <h3 class="box-title">{{ trans('labels.users') }} </h3>
                    <div class="pull-right">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Add Users</button>
                    </div>
                  </div>
                  
                  <!-- /.box-header -->
                  <div class="box-body">
                    <div class="row">
                      <div class="col-xs-12">
                              <div class="box box-info">
    <table class="table table-striped">
        <thead class="thead-ligh">
            <th>id</th>
            <th>Full Name</th>
            <th>Roles</th>
        </thead>
        <tbody>
            @if ($allusers)
            @foreach ($allusers as $item)
            <tr>
            <td>{{$item->id}}</td>
            <td>{{$item->name}}</td>
            <td>{{$item->roles->name}}</td>
                </tr>
            @endforeach
            @else
                <tr>
                    <td>Sorry no Users</td>
                </tr>
            @endif
        </tbody>
    </table>
</div>
                      </div>
                    </div></div></div></div></div></section>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Add Staff</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form class="form-horizontal" role="form" method="POST" action="{{ route('users.store') }}">
                {{ csrf_field() }}

                <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                    <label for="name" class="col-md-4 control-label">Name</label>

                    <div class="col-md-6">
                        <input id="name" type="text" class="form-control" name="name" value="{{ old('name') }}">

                        @if ($errors->has('name'))
                            <span class="help-block">
                                <strong>{{ $errors->first('name') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                    <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                    <div class="col-md-6">
                        <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}">

                        @if ($errors->has('email'))
                            <span class="help-block">
                                <strong>{{ $errors->first('email') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>
                <div class="form-group">
                    <label for="role" class="col-md-4 control-label">Assign Roles</label>
                    <div class="col-md-6">
                    <select class="form-control" name="role_id" id="">
                        @foreach ($roles as $item)
                    <option value="{{$item->id}}">{{$item->name}}</option>
                        @endforeach
                    </select>
                    </div>
                </div>
                <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                    <label for="password" class="col-md-4 control-label">Password</label>

                    <div class="col-md-6">
                        <input id="password" type="password" class="form-control" name="password">

                        @if ($errors->has('password'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

                <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error' : '' }}">
                    <label for="password-confirm" class="col-md-4 control-label">Confirm Password</label>

                    <div class="col-md-6">
                        <input id="password-confirm" type="password" class="form-control" name="password_confirmation">

                        @if ($errors->has('password_confirmation'))
                            <span class="help-block">
                                <strong>{{ $errors->first('password_confirmation') }}</strong>
                            </span>
                        @endif
                    </div>
                </div>

               
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">add User</button>
        </form>
        </div>
      </div>
    </div>
  </div>
@endsection 